### PR TITLE
Don't delete in-memory raster (fixes #160)

### LINKED ISSUE #160: Invalid use of rasterio in _warper leading to segmentation faults
A contextily user reported https://github.com/mapbox/rasterio/issues/2000 and I have confirmed the issue. There may be something I can do on the rasterio end, or in GDAL, but misuse of rasterio is at the heart of the matter.

The problem is in
https://github.com/geopandas/contextily/blob/96b0e5e4536a6167058d6b10a5f96ed6014c35e2/contextily/tile.py#L404-L419. When the `memfile` context manager exits, your `mraster` dataset will be deleted. The VRT you return from the function references a non-existent in-memory file.

The reason why no one saw the problem with rasterio versions < 1.1.6 is that `MemoryFile.close` had a bug and did not clean up in-memory datasets. That bug was fixed in 1.1.6.

### PR DESCRIPTION
**Pull request by drnextgis**

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
Whoops, we were doing the same .. -> https://github.com/geopandas/contextily/pull/163

**Comment by drnextgis** [comment]
Thanks @jorisvandenbossche! Closing in favor of your PR.

**Comment by jorisvandenbossche** [comment]
Hmm, but apparently mine is not fixing it completely .. (one of the two travis builds is still crashing)

**Comment by drnextgis** [comment]
I see. Any objections to my PR?

**Comment by jorisvandenbossche** [comment]
With an additional fix it is now working (needed to use the VRT with a context manager as well). I think I prefer my PR because I don't think it is needed to keep the memory file object alive after the warping.

Thanks for the contribution, and sorry again for the overlap in work!

**Pull request closed without merging**
