### PR TITLE
DOC: add notebook about working with local files

### PR DESCRIPTION
**Pull request by darribas**
Opening new PR with more notebook content:

- Local files notebook finished

I think from my side the only bit that'd be needed is to add a notebook for the deep dive on `add_basemap` but, the more I think about it, the less convinced I am that we need one. All the functionality is covered among the other notebooks (crs, providers and local files). The only value I'd see is to have more examples and all centralised in one notebook for `add_basemap`, but I'd be inclined to leave this as a good first issue for other contributors to jump on.

What do you think @jorisvandenbossche / @ljwolf ?

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
Looks good! 

I can't run the notebook locally (some incompatibility with the rasterio version I have locally, need to figure out my environment), so didn't push anything, but 2 tiny remarks:

- There are a few occurences of "GeoTIF" that should be "GeoTIFF"
- For the Polygon creation, using `box(west, south, east, north)` would be simpler (with `from shapely.geometry import box`).

**Comment by jorisvandenbossche** [comment]
@darribas I think this is fine to get merged? (I just had two minor comments, see above, for the rest a super notebook!)

**Comment by darribas** [comment]
Just pushed the suggestions, thanks very much!!! Yes, I think it's ready to merge. Thanks very much @jorisvandenbossche for the comments!

**Comment by jorisvandenbossche** [comment]
Cool!

**Pull request merged**
