### PR TITLE
Example interfacing GEE with contextily

### PR DESCRIPTION
**Pull request by darribas**
First stub, unfinished. Eventually, this PR will contain:

- [x] Notebook with example linking contextily to GEE (elevation model and ~~Sentinel 2~~ Landsat 8)
- [x] Hook to display the notebook on the website

Also, with this, we'd be starting the series of interfacing contextily with other packages. My suggestion here is to use the name of the notebook `friends_XXX.ipynb` where `XXX` is the package we show how to interface. So, for example, we could also have `friends_cenpy.ipynb`, `friends_osmnx.ipynb`, etc. These should also display ideally under a horizontal bar on the side menu of the website (would this be possible @jorisvandenbossche?).

Will confirm when this can be reviewed/merged.

### CODE REVIEW

**Comment by ljwolf** [comment]
We could throw a basemap on [this]?

**Comment by darribas** [comment]
OK I think the GEE is ready to go, at least for now. I've added it as a separate notebook but not separate (not sure how to do that)

**Comment by jorisvandenbossche** [comment]
To just add it to the sidebar on the doc site for now, you need to update:

* https://github.com/geopandas/contextily/blob/master/docs/index.rst -> add it to the toctree
* https://github.com/geopandas/contextily/blob/97d5f04e89a245edce91940a93d5f3f4e99cec07/docs/conf.py#L81-L89 -> add it to this list of files to copy

**Comment by darribas** [comment]
Added! This is ready for review.

**Pull request merged**
