### PR TITLE
Add Dockerfile for Binder

### PR DESCRIPTION
**Pull request by darribas**
Replacement for #137

### CODE REVIEW

**Comment by darribas** [comment]
You can check at:

https://mybinder.org/v2/gh/darribas/contextily/add_binder_docker?urlpath=lab/tree/notebooks/intro_guide.ipynb

**Comment by jorisvandenbossche** [comment]
Cool! Looks good, can you add the link to the README as I did in https://github.com/geopandas/contextily/pull/137 ?

Another question is which version we want to have installed with it: master or latest release? Since it are the notebooks on the master branch, it might need master of contextily to be able to run (which would need a `pip install git+https://github.com/geopandas/contextily.git@master` in the dockerfile

**Comment by darribas** [comment]
I've added the link to Binder on the `README` as you did on #137, I think that should work.

I don't think we need to install master to get the newest notebooks because those are added from the master repo in the `Dockerfile`, no? So every time a container is triggered, the most recent notebooks are included. I'd be keen on keeping them on the stable and released version for the `contextily` functionality.

**Comment by jorisvandenbossche** [comment]
> I'd be keen on keeping them on the stable and released version for the contextily functionality.

Well, that's not really possible if you want to directly add proper documentation in PRs adding new features (which is what ideally happens)

**Comment by darribas** [comment]
That's a good point, I'll add a line to the Dockerfile to install/upgrade contextily on the container through pip, should not be a problem (unless we increase tricky dependencies in the future, which I don't foresee).

**Comment by darribas** [comment]
Just pushed!

**Comment by jorisvandenbossche** [comment]
Let's try that out!

**Comment by jorisvandenbossche** [comment]
Binder link is working!

**Comment by jorisvandenbossche** [comment]
Although it seems to be using the conda-installed contextily, not the master version .. 
(something we can figure out later)

**Pull request merged**
