### PR TITLE
improve stability of ctx.add_basemap()

### LINKED ISSUE #247: Several errors with ctx.add_basemap()
I am using `ctx.add_basemap()` to spice up an [example notebook](https://github.com/Deltares/dfm_tools/blob/main/docs/notebooks/modelbuilder_example.ipynb) for a package I maintain. This package/function is really helpful so thanks for creating this. However, it is convenient if my notebook runs successfully at any moment in time, independent of contextily. Quite often, the notebook crashes because of a (server)timeout or different error in contextily that temporarily pops up. Today, I encountered the following error, which is not really reproducible at the moment:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[4], line 15
     13 mk_object.mesh2d_get().plot_edges(ax,zorder=1)
     14 bnd_gdf_interp.plot(ax=ax, edgecolor='r')
---> 15 ctx.add_basemap(ax=ax, crs=crs, attribution=False)
     16 dfmt.plot_coastlines(ax=ax, crs=crs)

File ~\Anaconda3\envs\dfm_tools_env\Lib\site-packages\contextily\plotting.py:134, in add_basemap(ax, zoom, source, interpolation, attribution, attribution_size, reset_extent, crs, resampling, zoom_adjust, **extra_imshow_args)
    130     left, right, bottom, top = _reproj_bb(
    131         left, right, bottom, top, crs, "epsg:3857"
    132     )
    133 # Download image
--> 134 image, extent = bounds2img(
    135     left, bottom, right, top, zoom=zoom, source=source, ll=False, zoom_adjust=zoom_adjust
    136 )
    137 # Warping
    138 if crs is not None:

File ~\Anaconda3\envs\dfm_tools_env\Lib\site-packages\contextily\tile.py:265, in bounds2img(w, s, e, n, zoom, source, ll, wait, max_retries, n_connections, use_cache, zoom_adjust)
    262 arrays = Parallel(n_jobs=n_connections, prefer=preferred_backend)(
    263     delayed(fetch_tile_fn)(tile_url, wait, max_retries) for tile_url in tile_urls)
    264 # merge downloaded tiles
--> 265 merged, extent = _merge_tiles(tiles, arrays)
    266 # lon/lat extent --> Spheric Mercator
    267 west, south, east, north = extent

File ~\Anaconda3\envs\dfm_tools_env\Lib\site-packages\contextily\tile.py:660, in _merge_tiles(tiles, arrays)
    657 indices = tile_xys - tile_xys.min(axis=0)
    659 # the shape of individual tile images
--> 660 h, w, d = arrays[0].shape
    662 # number of rows and columns in the merged tile
    663 n_x, n_y = (indices + 1).max(axis=0)

AttributeError: 'NoneType' object has no attribute 'shape'
```

I think this should be possible to reproduce this with this simpler code:
```python
import matplotlib.pyplot as plt
plt.close('all')
import contextily as ctx

lon_min, lon_max, lat_min, lat_max = 105.8, 106.85, 17.75, 18.5

fig, ax = plt.subplots()
ax.set_xlim(lon_min, lon_max)
ax.set_ylim(lat_min, lat_max)

ctx.add_basemap(ax=ax, crs='EPSG:4326')
```

I understand that this is not a useful issue description since it is not reproducible yet. However, I would like to have it as a placeholder so I can immediately report related follow-up issues in the future. Feel free to close it as "won't do", it can be re-opened when relevant. My ideal situation would be that this function is more robust and does not crash every few weeks. Until then, I will comment usage in my example notebook in order to not bother users with it.

### PR DESCRIPTION
**Pull request by veenstrajelmer**
Fixes #247

Changed:
* made sure all `HTTPError`s are captured and retried
* included the last error/reason message when max_retries is reached

The code in this contribution catches all `HTTPError`s and therefore makes it impossible that the code continue with `None` in the `arrays` list. This used to cause varying errors related to `None`, depending on whether the first in the `arrays` list was `None` or not, or any of the others. By capturing all HTTPErrors, the code is redirected to retrying instead of that the `_retryer()` function returns None. After `max_retries` is reached, the user now gets a informative error message. The format of the message is based on what `request.raise_for_status()` would return.

The current code proves useful, these were the error messages during the manual tests:
- `HTTPError: Connection reset by peer too many times. Last message was: 502 Error: Bad Gateway for url: https://a.tile.openstreetmap.fr/hot/10/812/458.png`
- `500 Error` (forgot to copy this one when it occurred

@martinfleis could you review this PR?

### CODE REVIEW

**Comment by veenstrajelmer** [comment]
I see some of the tests are failing because of `os.wait()` already taken care of in https://github.com/geopandas/contextily/pull/245. But that PR also has failing tests related to this PR. If you would merge #245 I can update the branch if required, but I leave it to you to decide about the way forward of course.

**Comment by martinfleis** [comment]
I've merged #245, you can try updating this one

**Comment by veenstrajelmer** [comment]
The branch/fork was synced, but I think you have to approve the test workflow to be kicked off again.

**Comment by martinfleis** [comment]
I believe that the remaining failures are not related.

**Review by martinfleis — APPROVED** [review]
I don't think there's a way of testing this easily so let's say this is fine as is, unless you want to tweak it further.

**Comment by veenstrajelmer** [comment]
Ok, in that case please go ahead with merging the PR. Thanks for your consideration. I would like to update the minimal contextily version in my pyproject.toml once this fix is released. Is it already know when there will be a new release or not yet?

**Comment by martinfleis** [comment]
I'll cut the patch release today.

**Pull request merged**
