### PR TITLE
Add binder link

### PR DESCRIPTION
**Pull request by jorisvandenbossche**

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
Test link from this branch: https://mybinder.org/v2/gh/jorisvandenbossche/contextily/binder-link?urlpath=lab/tree/notebooks/intro_guide.ipynb

**Comment by jorisvandenbossche** [comment]
So the "annoying" thing here is that I needed to add another environment.yml file .. We can't use the one of the docs because that one doesn't include the additional dependencies we need to run the notebooks (eg geopandas, and I want to keep that out of the other env file to keep it light for readthedocs). 
We also can't just rely on the `setup.py`, for the same reason, since eg geopandas is not a dependency of contextily.

**Comment by darribas** [comment]
What if we added a Dockerfile that pulls the [`gds_py`](https://github.com/darribas/gds_env/tree/master/gds_py)? That's what I do for [the book](https://github.com/gdsbook/book/blob/master/Dockerfile) and works pretty well. If so, I'm happy to issue a PR setting it up.

**Comment by jorisvandenbossche** [comment]
That's fine for me as well!

**Comment by darribas** [comment]
OK, on over at #138

**Pull request closed without merging**
