### PR TITLE
MAINT: update infrastructure

### PR DESCRIPTION
**Pull request by martinfleis**
Moving to pyproject.toml and setuptools_scm.

I have also included GHA to do the relase, but for that I will need one of the PyPI maintainers (@jorisvandenbossche, @darribas, @ljwolf) to add the access token as a `PYPI_API_TOKEN` secret.

### CODE REVIEW

**Comment by martinfleis** [comment]
Failures here are unrelated. I think that OSM HOT is being continuously updated based on the latest status of OSM so our hard-coded tests will need to be adapted.

**Comment by jorisvandenbossche** [comment]
Looking into a token right now

**Comment by jorisvandenbossche** [comment]
Token has been set up. 

For the failing tests, should we try to kind of mock a server with some files added as test data, so that those are stable? 
But we can maybe leave that for after a quick release, and relax the three failing tests for now?

**Comment by martinfleis** [comment]
I have relaxed the tests now. If this passes I'l merge, push changelog and cut a release to fix the numerous downstream breakages.

**Comment by martinfleis** [comment]
We don't have a changelog here... so I'll just cut the release.

**Comment by jorisvandenbossche** [comment]
Thanks! (and you can add some notes to the github release)

**Pull request merged**
